// Package store — dialect abstraction so the same query layer works on both
// SQLite (modernc.org/sqlite) and PostgreSQL (jackc/pgx). The conn wrapper
// rebinds '?' placeholders to '$n' for Postgres and bridges the last-insert-id
// vs RETURNING difference, so the ~95 existing query strings stay unchanged.
package store

import (
	"database/sql"
	"fmt"
	"strconv"
	"strings"
)

// Dialect identifies the active SQL backend.
type Dialect int

const (
	SQLite Dialect = iota
	Postgres
)

func (d Dialect) String() string {
	if d == Postgres {
		return "postgres"
	}
	return "sqlite"
}

// Rebind converts '?' positional placeholders to the dialect's form: SQLite uses
// '?' (returned unchanged), Postgres uses $1,$2,… in order. Safe here because the
// codebase never embeds a literal '?' inside an SQL string (placeholders only).
func (d Dialect) Rebind(query string) string {
	if d != Postgres {
		return query
	}
	var b strings.Builder
	b.Grow(len(query) + 8)
	n := 0
	for i := 0; i < len(query); i++ {
		if query[i] == '?' {
			n++
			b.WriteByte('$')
			b.WriteString(strconv.Itoa(n))
			continue
		}
		b.WriteByte(query[i])
	}
	return b.String()
}

// ---- DDL type tokens (build schema valid on both backends) ----

// AutoIncPK is the definition of an auto-incrementing 64-bit integer primary key
// named "id".
func (d Dialect) AutoIncPK() string {
	if d == Postgres {
		return "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	}
	return "id INTEGER PRIMARY KEY AUTOINCREMENT"
}

// Blob is the raw byte-array column type.
func (d Dialect) Blob() string {
	if d == Postgres {
		return "BYTEA"
	}
	return "BLOB"
}

// VectorCol is the column type for an embedding of the given dimension. Postgres
// uses pgvector's native type; SQLite stores the float32 bytes as a BLOB.
func (d Dialect) VectorCol(dims int) string {
	if d == Postgres {
		return fmt.Sprintf("vector(%d)", dims)
	}
	return "BLOB"
}

// EpochToDate renders an expression converting a unix-seconds INTEGER column to a
// local date.
func (d Dialect) EpochToDate(col string) string {
	if d == Postgres {
		return fmt.Sprintf("to_timestamp(%s)::date", col)
	}
	return fmt.Sprintf("DATE(%s, 'unixepoch', 'localtime')", col)
}

// AddColumn renders an "ADD COLUMN" clause that is idempotent where supported.
// Postgres supports IF NOT EXISTS; SQLite does not (callers ignore the duplicate
// error instead).
func (d Dialect) AddColumn() string {
	if d == Postgres {
		return "ADD COLUMN IF NOT EXISTS"
	}
	return "ADD COLUMN"
}

// ---- Querier: the rebinding handle shared with the subsystem packages ----

// Querier is the database handle used by the subsystem stores (rules, providers,
// reliability, vectorstore, memory). Implementations rebind placeholders for the
// active dialect, so callers keep writing '?' regardless of backend.
type Querier interface {
	Exec(query string, args ...any) (sql.Result, error)
	Query(query string, args ...any) (*sql.Rows, error)
	QueryRow(query string, args ...any) *sql.Row
	// InsertReturningID runs an INSERT and returns the new row's "id".
	InsertReturningID(query string, args ...any) (int64, error)
	Dialect() Dialect
}

// conn wraps a *sql.DB with dialect-aware rebinding. It satisfies Querier and
// also exposes the few raw-handle methods store/db.go needs (Begin/Close/Stats).
type conn struct {
	db      *sql.DB
	dialect Dialect
}

func newConn(db *sql.DB, d Dialect) *conn { return &conn{db: db, dialect: d} }

// NewQuerier wraps a raw *sql.DB as a dialect-aware Querier. Useful for tests and
// for callers that manage their own *sql.DB connection.
func NewQuerier(db *sql.DB, d Dialect) Querier { return newConn(db, d) }

func (c *conn) Dialect() Dialect { return c.dialect }

func (c *conn) Exec(query string, args ...any) (sql.Result, error) {
	return c.db.Exec(c.dialect.Rebind(query), args...)
}

func (c *conn) Query(query string, args ...any) (*sql.Rows, error) {
	return c.db.Query(c.dialect.Rebind(query), args...)
}

func (c *conn) QueryRow(query string, args ...any) *sql.Row {
	return c.db.QueryRow(c.dialect.Rebind(query), args...)
}

// InsertReturningID inserts and returns the generated id. SQLite uses
// LastInsertId(); Postgres has no such concept, so we append RETURNING id.
func (c *conn) InsertReturningID(query string, args ...any) (int64, error) {
	if c.dialect == Postgres {
		var id int64
		err := c.db.QueryRow(c.dialect.Rebind(query)+" RETURNING id", args...).Scan(&id)
		return id, err
	}
	res, err := c.db.Exec(c.dialect.Rebind(query), args...)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// Begin starts a transaction on the underlying handle. Callers must rebind any
// '?' placeholders themselves via Dialect().Rebind (only InsertRequest uses this).
func (c *conn) Begin() (*sql.Tx, error) { return c.db.Begin() }

// Close closes the underlying handle.
func (c *conn) Close() error { return c.db.Close() }

// Stats exposes the underlying connection-pool statistics.
func (c *conn) Stats() sql.DBStats { return c.db.Stats() }

// splitSQLStatements drops full-line comments and blank lines from a multi-
// statement schema string, then splits it into individual statements on ';'.
// Used so a schema literal can be executed one statement at a time — pgx does
// not run multiple statements in a single Exec. Safe here: the schema contains
// no ';' inside string literals.
func splitSQLStatements(schema string) []string {
	var sb strings.Builder
	for _, line := range strings.Split(schema, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "--") {
			continue
		}
		sb.WriteString(line)
		sb.WriteByte('\n')
	}
	var out []string
	for _, stmt := range strings.Split(sb.String(), ";") {
		if strings.TrimSpace(stmt) != "" {
			out = append(out, stmt)
		}
	}
	return out
}
